spring.application.name=liteapi-backend

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Server configuration
server.port=8080

# LiteAPI configuration
liteapi.base-url=https://api.liteapi.travel/v3.0
# REMPLACEZ "VOTRE_CLE_API" PAR VOTRE VRAIE CLE LITEAPI :
liteapi.api-key=sand_c0fb3712-c0b7-4abc-b646-9ea7bea56dbf